/**
 */
package airport.areas.provider;

import airport.areas.util.AreasAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AreasItemProviderAdapterFactory extends AreasAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AreasItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.Arrival} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrivalItemProvider arrivalItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.Arrival}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrivalAdapter() {
		if (arrivalItemProvider == null) {
			arrivalItemProvider = new ArrivalItemProvider(this);
		}

		return arrivalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.BaggageClaim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaggageClaimItemProvider baggageClaimItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.BaggageClaim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaggageClaimAdapter() {
		if (baggageClaimItemProvider == null) {
			baggageClaimItemProvider = new BaggageClaimItemProvider(this);
		}

		return baggageClaimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.BaggageDropOff} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaggageDropOffItemProvider baggageDropOffItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.BaggageDropOff}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaggageDropOffAdapter() {
		if (baggageDropOffItemProvider == null) {
			baggageDropOffItemProvider = new BaggageDropOffItemProvider(this);
		}

		return baggageDropOffItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.Departure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DepartureItemProvider departureItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.Departure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDepartureAdapter() {
		if (departureItemProvider == null) {
			departureItemProvider = new DepartureItemProvider(this);
		}

		return departureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.DropOff} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DropOffItemProvider dropOffItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.DropOff}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDropOffAdapter() {
		if (dropOffItemProvider == null) {
			dropOffItemProvider = new DropOffItemProvider(this);
		}

		return dropOffItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.GateArea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GateAreaItemProvider gateAreaItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.GateArea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGateAreaAdapter() {
		if (gateAreaItemProvider == null) {
			gateAreaItemProvider = new GateAreaItemProvider(this);
		}

		return gateAreaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.ParkingArea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParkingAreaItemProvider parkingAreaItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.ParkingArea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParkingAreaAdapter() {
		if (parkingAreaItemProvider == null) {
			parkingAreaItemProvider = new ParkingAreaItemProvider(this);
		}

		return parkingAreaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link airport.areas.TransportationServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransportationServicesItemProvider transportationServicesItemProvider;

	/**
	 * This creates an adapter for a {@link airport.areas.TransportationServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransportationServicesAdapter() {
		if (transportationServicesItemProvider == null) {
			transportationServicesItemProvider = new TransportationServicesItemProvider(this);
		}

		return transportationServicesItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (arrivalItemProvider != null) arrivalItemProvider.dispose();
		if (baggageClaimItemProvider != null) baggageClaimItemProvider.dispose();
		if (baggageDropOffItemProvider != null) baggageDropOffItemProvider.dispose();
		if (departureItemProvider != null) departureItemProvider.dispose();
		if (dropOffItemProvider != null) dropOffItemProvider.dispose();
		if (gateAreaItemProvider != null) gateAreaItemProvider.dispose();
		if (parkingAreaItemProvider != null) parkingAreaItemProvider.dispose();
		if (transportationServicesItemProvider != null) transportationServicesItemProvider.dispose();
	}

}
